### ISSUE TITLE
Compatibility Matrix out of date

### ISSUE THREAD

**Issue by abbyachau** [pivotal-cf/docs-pcf-pipelines#11]
Hey there, can't remember where we landed with this but it looks like the Compatibility Matrix is out of date, can we pls link out to our README instead since we update that regularly? We are on v21 now and the docs refer to v18. Thanks!

https://staging-pcf-pipelines-152208226.cfapps.io/myservice/index.html

https://github.com/pivotal-cf/pcf-pipelines#install-pcf-pipelines

**Comment by kdolor-pivotal** [comment]
This is now included in `index.html`
