### ISSUE TITLE
Add pipeline image to install-pcf page for vSphere

### ISSUE THREAD

**Issue by abbyachau** [pivotal-cf/docs-pcf-pipelines#14]
Hey there, would it be possible please to add the following image: 
https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/vsphere/embed.png
to:
https://staging-pcf-pipelines-152208226.cfapps.io/myservice/vsphere-pipeline-install.html
Thanks!

**Comment by mlimonczenko** [comment]
Hello @abbyachau ,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
