### ISSUE TITLE
Add images to GCP and Upgrade Tile pipelines

### ISSUE THREAD

**Issue by abbyachau** [pivotal-cf/docs-pcf-pipelines#17]
Please can we add the following images to the GCP and Upgrade Tile pipelines

GCP image: https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/gcp/embed.png
Page: https://staging-pcf-pipelines-152208226.cfapps.io/myservice/gcp-install-pipeline.html

Upgrade Tile image:  <img width="1327" alt="screen shot 2017-12-01 at 15 29 06" src="https://user-images.githubusercontent.com/15200487/33508099-395cff70-d6ad-11e7-9079-3f3ceaf24ce1.png">
Page: https://staging-pcf-pipelines-152208226.cfapps.io/myservice/upgrade-tile.html

**Comment by mlimonczenko** [comment]
Hello @abbyachau,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
