### ISSUE TITLE
upgrade pipeline overview example can be more human readable

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-pcf-pipelines#5]
https://staging-pcf-pipelines-152208226.cfapps.io/myservice/upgrade-tile.html#overview
the n+1 examples are confusing and hard to read. Suggest change to a real example so it is more human readable.

```
For example, if a new tile is released going from either –.n.– to –.n+1.– or n.–.– to n+1.–.–, the pipeline will not upgrade to these tile versions. The Upgrade Tile pipeline will only upgrade from –.–.n to –.–.n+1 tile versions.
```

```
For example, if a new tile is released going from either 1.10.x to 1.11.x or 1.x.x to 2.x.x, the pipeline will not upgrade to these tile versions. The Upgrade Tile pipeline will only upgrade from 1.10.1 to 1.10.2 tile versions.
```

**Comment by mlimonczenko** [comment]
Hello @randomtask1155,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
