### ISSUE TITLE
wipe-env description is too generic

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-pcf-pipelines#6]
https://staging-pcf-pipelines-152208226.cfapps.io/myservice/gcp-install-pipeline.html#config

wipe-env `This job teard down your Pivotal Cloud Foundry deployment.` could be more specific.  For example does it delete opsman?  Users should know specifically what gets deleted by this job.

**Comment by mlimonczenko** [comment]
Hello @randomtask1155,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
