### ISSUE TITLE
Add command to kick off wipe-env job

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pcf-pipelines#7]
Under each install pipeline the procedures are categorized as 

```
Overview
Pipeline Configuration
Installing PCF on vSphere
```
From documentation perspective it will be good to see another topic of removing the installation, with sample `fly` commands. Also, detailing what wipe-env does as mentioned [here](https://github.com/pivotal-cf/docs-pcf-pipelines/issues/6)

**Comment by mlimonczenko** [comment]
Hello @outofmem0ry,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
