### ISSUE TITLE
More information on why we might need to kickoff the  first job manually vs automatically

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pcf-pipelines#8]
On [this page](https://staging-pcf-pipelines-152208226.cfapps.io/myservice/vsphere-pipeline-install.html#usage), in the last line it is mentioned that `The first job will either trigger automatically or require manual intervention`. Curious what is the reason behind it, also this question might pop up with other users as well. Is this because of the `pivnet resource type not found issue`

**Comment by mlimonczenko** [comment]
Hello @outofmem0ry,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
