### ISSUE TITLE
Details regarding other pipelines like upgrade-buildpack.

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pcf-pipelines#9]
In the pcf-pipeline release there are other pipelines like upgrade-buildpack etc. Are they within the scope of this documents or still to be added ?

**Comment by mlimonczenko** [comment]
Hello @outofmem0ry,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
